openapi: 3.0.1
info:
  title: '@jupiterone/graph-veracode'
  description: JupiterOne Veracode Integration
  x-cortex-git:
    github:
      repository: JupiterOne/graph-veracode
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-service-groups: tier-4
  x-cortex-tag: '@jupiterone/graph-veracode'
